"""futurefunded tenant ownership and onboarding drafts

Revision ID: 099736a5a455
Revises: 771c31231115
Create Date: 2026-03-06 23:16:28.484439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099736a5a455'
down_revision = '771c31231115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ff_tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('org_type', sa.String(length=64), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('public_slug', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('brand_primary', sa.String(length=7), nullable=False),
    sa.Column('brand_accent', sa.String(length=7), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ff_tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ff_tenants_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ff_tenants_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ff_tenants_owner_email'), ['owner_email'], unique=False)
        batch_op.create_index('ix_ff_tenants_owner_status', ['owner_email', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ff_tenants_public_slug'), ['public_slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_ff_tenants_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_ff_tenants_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ff_tenants_updated_at'), ['updated_at'], unique=False)

    op.create_table('ff_onboarding_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('public_slug', sa.String(length=160), nullable=True),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('org_type', sa.String(length=64), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.String(length=32), nullable=False),
    sa.Column('checkout', sa.String(length=64), nullable=False),
    sa.Column('brand_primary', sa.String(length=7), nullable=False),
    sa.Column('brand_accent', sa.String(length=7), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['ff_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ff_onboarding_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ff_onboarding_drafts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ff_onboarding_drafts_org_name'), ['org_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ff_onboarding_drafts_owner_email'), ['owner_email'], unique=False)
        batch_op.create_index('ix_ff_onboarding_drafts_owner_status', ['owner_email', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ff_onboarding_drafts_public_slug'), ['public_slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_ff_onboarding_drafts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_ff_onboarding_drafts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ff_onboarding_drafts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_ff_onboarding_drafts_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ff_onboarding_drafts_updated_at'), ['updated_at'], unique=False)

    op.create_table('ff_tenant_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['ff_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_ff_tenant_users_tenant_email')
    )
    with op.batch_alter_table('ff_tenant_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ff_tenant_users_email'), ['email'], unique=False)
        batch_op.create_index('ix_ff_tenant_users_email_role', ['email', 'role'], unique=False)
        batch_op.create_index(batch_op.f('ix_ff_tenant_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_ff_tenant_users_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ff_tenant_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ff_tenant_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ff_tenant_users_role'))
        batch_op.drop_index('ix_ff_tenant_users_email_role')
        batch_op.drop_index(batch_op.f('ix_ff_tenant_users_email'))

    op.drop_table('ff_tenant_users')
    with op.batch_alter_table('ff_onboarding_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ff_onboarding_drafts_updated_at'))
        batch_op.drop_index('ix_ff_onboarding_drafts_tenant_status')
        batch_op.drop_index(batch_op.f('ix_ff_onboarding_drafts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ff_onboarding_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_ff_onboarding_drafts_slug'))
        batch_op.drop_index(batch_op.f('ix_ff_onboarding_drafts_public_slug'))
        batch_op.drop_index('ix_ff_onboarding_drafts_owner_status')
        batch_op.drop_index(batch_op.f('ix_ff_onboarding_drafts_owner_email'))
        batch_op.drop_index(batch_op.f('ix_ff_onboarding_drafts_org_name'))
        batch_op.drop_index(batch_op.f('ix_ff_onboarding_drafts_created_at'))

    op.drop_table('ff_onboarding_drafts')
    with op.batch_alter_table('ff_tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ff_tenants_updated_at'))
        batch_op.drop_index(batch_op.f('ix_ff_tenants_status'))
        batch_op.drop_index(batch_op.f('ix_ff_tenants_slug'))
        batch_op.drop_index(batch_op.f('ix_ff_tenants_public_slug'))
        batch_op.drop_index('ix_ff_tenants_owner_status')
        batch_op.drop_index(batch_op.f('ix_ff_tenants_owner_email'))
        batch_op.drop_index(batch_op.f('ix_ff_tenants_name'))
        batch_op.drop_index(batch_op.f('ix_ff_tenants_created_at'))

    op.drop_table('ff_tenants')
    # ### end Alembic commands ###
