from __future__ import annotations

# -----------------------------------------------------------------------------
# Team Model
# Branding, theme config, roster/stats, SEO assets, and fundraising links.
#
# Key change:
# - Uses sa.JSON() with a Postgres JSONB variant (cross-db)
# - Pairs well with an Alembic env.py render_item override to avoid
#   JSONB(astext_type=Text()) in autogenerated migrations.
# -----------------------------------------------------------------------------

import copy
import uuid
from typing import TYPE_CHECKING, Any, TypedDict

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.extensions import db
from .mixins import SoftDeleteMixin, TimestampMixin

if TYPE_CHECKING:
    from .campaign_goal import CampaignGoal
    from .donation import Donation
    from .player import Player
    from .sponsor import Sponsor


class ImpactStat(TypedDict, total=False):
    label: str
    value: int


TEAM_CONFIG_DEFAULT: dict[str, Any] = {
    "slug": "connect-atx-elite",
    "team_name": "Connect ATX Elite",
    "meta_description": "Connect ATX Elite is a community-powered 12U AAU program.",
    "lang_code": "en",
    "theme": "dark",
    "theme_color": "#fbbf24",
    "record": {
        "regional": {"wins": 15, "losses": 3},
        "national": {"wins": 17, "losses": 4},
    },
    "impact_stats": [
        {"label": "Players Enrolled", "value": 16},
        {"label": "Honor Roll Scholars", "value": 11},
        {"label": "Tournaments Played", "value": 12},
        {"label": "Years Running", "value": 3},
    ],
}

# Cross-DB JSON type:
# - SQLite: JSON
# - Postgres: JSONB
JSON_TYPE = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


class Team(db.Model, TimestampMixin, SoftDeleteMixin):
    """Brand & theme configuration for a team, plus roster, sponsors & stats."""

    __tablename__ = "teams"

    # ── Identity ────────────────────────────────────────────────
    id: Mapped[int] = mapped_column(sa.Integer, primary_key=True)

    uuid: Mapped[str] = mapped_column(
        sa.String(36),
        unique=True,
        nullable=False,
        default=lambda: str(uuid.uuid4()),
        index=True,
    )

    slug: Mapped[str] = mapped_column(sa.String(80), unique=True, nullable=False, index=True)
    team_name: Mapped[str] = mapped_column(sa.String(120), nullable=False)

    meta_description: Mapped[str | None] = mapped_column(sa.String(255), nullable=True)
    lang_code: Mapped[str] = mapped_column(sa.String(5), nullable=False, default="en")

    # ── Theming ─────────────────────────────────────────────────
    theme: Mapped[str | None] = mapped_column(sa.String(30), nullable=True)
    theme_color: Mapped[str | None] = mapped_column(sa.String(7), nullable=True)

    # ── SEO & Social (optional) ─────────────────────────────────
    og_title: Mapped[str | None] = mapped_column(sa.String(120), nullable=True)
    og_description: Mapped[str | None] = mapped_column(sa.String(255), nullable=True)
    og_image: Mapped[str | None] = mapped_column(sa.String(255), nullable=True)
    favicon: Mapped[str | None] = mapped_column(sa.String(255), nullable=True)
    apple_icon: Mapped[str | None] = mapped_column(sa.String(255), nullable=True)

    # ── Page Defaults ───────────────────────────────────────────
    hero_image: Mapped[str | None] = mapped_column(sa.String(255), nullable=True)
    custom_css: Mapped[str | None] = mapped_column(sa.String(255), nullable=True)

    # ── Record & Impact Stats (JSON) ────────────────────────────
    record: Mapped[dict[str, Any]] = mapped_column(
        JSON_TYPE,
        nullable=False,
        default=lambda: copy.deepcopy(TEAM_CONFIG_DEFAULT["record"]),
    )

    impact_stats: Mapped[list[ImpactStat] | None] = mapped_column(
        JSON_TYPE,
        nullable=True,
        default=lambda: copy.deepcopy(TEAM_CONFIG_DEFAULT["impact_stats"]),
    )

    # ── Relationships ───────────────────────────────────────────
    players: Mapped[list[Player]] = relationship(
        "Player",
        back_populates="team",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    sponsors: Mapped[list[Sponsor]] = relationship(
        "Sponsor",
        back_populates="team",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    # CampaignGoal.team_id is optional (ondelete=SET NULL) → do NOT use delete-orphan.
    campaign_goals: Mapped[list[CampaignGoal]] = relationship(
        "CampaignGoal",
        back_populates="team",
        lazy="selectin",
        passive_deletes=True,
    )

    # Donations are financial records → do NOT use delete-orphan.
    donations: Mapped[list[Donation]] = relationship(
        "Donation",
        back_populates="team",
        lazy="selectin",
        passive_deletes=True,
    )

    # ── Serialization ───────────────────────────────────────────
    def as_dict(self, include_players: bool = True) -> dict[str, Any]:
        data: dict[str, Any] = {
            "id": self.id,
            "uuid": self.uuid,
            "slug": self.slug,
            "team_name": self.team_name,
            "meta_description": self.meta_description,
            "lang_code": self.lang_code,
            "theme": self.theme,
            "theme_color": self.theme_color,
            "og_title": self.og_title,
            "og_description": self.og_description,
            "og_image": self.og_image,
            "favicon": self.favicon,
            "apple_icon": self.apple_icon,
            "hero_image": self.hero_image,
            "custom_css": self.custom_css,
            "record": self.record,
            "impact_stats": self.impact_stats,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }

        if include_players:
            data["players"] = [p.as_dict() for p in (self.players or [])]

        return data

    # ── Helpers ─────────────────────────────────────────────────
    @classmethod
    def get_or_create_default(cls) -> Team:
        team = cls.query.first()
        if not team:
            team = cls(**copy.deepcopy(TEAM_CONFIG_DEFAULT))
            db.session.add(team)
            db.session.commit()
        return team

    def add_player(self, name: str, role: str | None = None, photo_url: str | None = None) -> Player:
        from .player import Player

        player = Player(name=name, role=role, photo_url=photo_url, team=self)
        db.session.add(player)
        return player

    def update_from_dict(self, updates: dict[str, Any]) -> None:
        allowed = {
            "slug",
            "team_name",
            "meta_description",
            "lang_code",
            "theme",
            "theme_color",
            "og_title",
            "og_description",
            "og_image",
            "favicon",
            "apple_icon",
            "hero_image",
            "custom_css",
            "record",
            "impact_stats",
        }
        for field, value in updates.items():
            if field in allowed:
                setattr(self, field, value)

    def __repr__(self) -> str:
        return f"<Team {self.slug} ({self.team_name})>"

